# Name of website
title: RPUFOS

description: Retro Programmers United For Obsure Systems (RPUFOS). Study of ancient Obscure Systems that have fallen into oblivion.

# URL configuration
url: "https://VFD.github.io"
baseurl: "/RPUFOS"

# Build settings
timezone: "Europe/Paris"

# Conversion
markdown: kramdown

# Parameter to display future posts (use with caution)
# future: true

# Exclude
exclude:
    - .vscode/
    - .github/
