# Name of website
title: Exelvision

description: Retro Programmers United For Obsure Systems (RPUFOS). Study of ancient Obscure Systems that have fallen into oblivion.

# Leave blank for a user site or set "/project-name" for a project site
url: "https://VFD.github.io"

baseurl: "/RPUFOS"


# Configuration de la pagination
paginate: 10
paginate_path: "/page:num/"

# Plugins (GitHub Pages prend en charge jekyll-paginate par défaut)
plugins:
  - jekyll-paginate


# Build settings
timezone: "Europe/Paris"


# Conversion
markdown: kramdown


# Exclude
exclude:
    - .vscode/
    - .github/



